name: Micro Framework Test Tool
on:
    workflow_dispatch:
        inputs:
            version:
                description: "Micro Framework version"
                required: true
                default: "1.7"
                type: choice
                options:
                    - "1.7"
            php:
                description: "PHP version"
                required: true
                default: "8.4"
                type: choice
                options:
                    - "8.4"
            component:
                description: "Component"
                required: true
                default: "All"
                type: choice
                options:
                    - "All"
jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout meta repo
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ github.event.inputs.php }}
                    tools: composer
            -   name: Run orchestrator
                run: |
                    if [ "${{ github.event.inputs.component }}" = "All" ]; then
                      php orchestrator.php --version "${{ github.event.inputs.version }}"
                    else
                      php orchestrator.php \
                        --version "${{ github.event.inputs.version }}" \
                        --component "${{ github.event.inputs.component }}"
                    fi
